# Kickstart container config file - see https://gitub.com/infracamp/kickstart
# Run ./kickstart.sh to start a development-container for this project
version: 1
from: "ghcr.io/nfra-project/kickstart-flavor-php:8.1"

packages: [php8.1-curl, php8.1-http, php8.1-raphf, php8.1-redis, php8.1-sqlite]
command:
  build:
    - "composer update"
  init:
  test:
    - "vendor/bin/phpunit --bootstrap vendor/autoload.php --testdox test"
  run:
  dev:
    - "echo 'I am executed in dev mode'"
